import Head from "next/head";
import {
  AiFillGithub,
  AiFillLinkedin,
  AiFillInstagram,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/dev-ed-wave.jpeg";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">MyJourney</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="#">
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Emi Mano
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              CS student
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
            I'm a passionate computer science student with a keen interest 
            in front-end development technologies. I'm excited to embark on 
            my journey in this field and explore the fascinating world of 
            web development. Join me as I 
            learn, grow, and share my experiences along the way!
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <AiFillGithub />
              <AiFillLinkedin />
              <AiFillInstagram />
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={deved} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">My journey in Tech</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            From the early days of my journey, I discovered my passion for web development by creating a
              <span className="text-teal-500"> shopping website </span> during high school.
              Since then, I have been dedicated to expanding my knowledge and skills in <span className="text-teal-500">HTML,CSS and JavaScript </span>
              , constantly seeking to enhance my understanding of these foundational technologies.
              Currently, my focus is on delving deeper into React and learning more about other tools and frameworks such as C# and UI/UX design. I'm excited to explore the world of React, harness the power of C#, and master the art of creating intuitive and user-friendly interfaces.


            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            Join me as I continue my journey of growth and discovery, immersing 
            myself in the ever-evolving field of front-end development and
             pushing the boundaries of what's possible in web development!"
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={design} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Beautiful Designs
              </h3>
              <p className="py-2">
                Creating elegant designs suited for every needs following core
                design theory.
              </p>
              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
              <p className="text-gray-800 py-1">Canva</p>
              <p className="text-gray-800 py-1">Figma</p>
              
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={code} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Code your dream project
              </h3>
              <p className="py-2">
              Are you looking to bring your next great website idea to life? Look no further! As a passionate front-end developer and aspiring UI/UX designer, I'm here to help turn your vision into a reality.
              </p>
              <h4 className="py-4 text-teal-600">The Technologies I Use</h4>
              <p className="text-gray-800 py-1">HTML</p>
              <p className="text-gray-800 py-1">CSS</p>
              <p className="text-gray-800 py-1">JavaScript</p>
              <p className="text-gray-800 py-1">React</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={consulting} width={100} height={100} />
              <h3 className="py-4 text-teal-600 ">The roles i am open to</h3>
              <p className="py-2">
              I am actively seeking job opportunities that allow me 
              to apply my skills and passion for front-end development.
              </p>
              
              <p className="text-gray-800 py-1">Front-end Developer</p>
              <p className="text-gray-800 py-1">UI/UX Designer</p>
              <p className="text-gray-800 py-1">React Developer</p>
              <p className="text-gray-800 py-1">Web Designer</p>
              <p className="text-gray-800 py-1">Front-end Engineer</p>
              
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Portofolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            Throughout my journey as a computer science student, I have embarked on 
            diverse projects, encompassing a 
            wide range of disciplines. Some notable highlights include:
              <span className="text-teal-500"> Exploring Design Patterns with Java, Embracing Unit Testing </span>,
              taking on the role of <span className="text-teal-500"> Scrum Master: </span> This role allowed me to develop my leadership and project management skills, facilitating effective collaboration and ensuring 
              the project's success through agile methodologies.
              Recently, my passion for front-end development led me to immerse myself in <span className="text-teal-500"> React </span>. 
              I dedicated significant time and effort to mastering this powerful JavaScript library, leveraging its 
              capabilities to create dynamic and interactive user interfaces. 
              
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Here are some of my projects:
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web1}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web2}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web3}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web4}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web5}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web6}
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
